/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  //  create a sidebar manually
  
  tutorialSidebar: [
     {
      type: 'category',
      label: 'Bienvenido',
      link: {
        type: 'generated-index',
        title: 'Manual OMS Compass',
        description: 'Tu guía de OMS COMPASS',
        slug: '/introduccion',
      },
      items: ['Activar-confirmaciones-OMS/Activar-confirmaciones-OMS',
       'Asignacion-Pictet-DVP/Asignacion-Pictet-DVP',
       'Generación-masiva-de-preordenes/Generación-masiva-de-preordenes'
      ],
    },
  ], 
  
   
};

export default sidebars;
